numerical_features = [
    'MAX_CREDIT', 'CREDIT_LIMIT', 'PAYMENT_AMOUNT', 'TOTAL_PAYMENTS',
    'DELAYED_PAYMENTS', 'CURRENT_PAYMENT', 'WORST_DELAY',
    'CURRENT_BALANCE', 'BALANCE_DUE', 'BALANCE_DUE_WORST_DELAY',
    'PERCENTAGE_OF_CREDIT_LIMIT_USED','MAX_CREDIT_GREATER_THAN_CREDIT_LIMIT',
    'HAS_DELAYED_PAYMENTS', 'HAS_WORST_DELAY', 'IS_CLOSED_LOAN',
    'LOAN_DURATION', 'TIME_TO_WORST_DELAY'
    ]
categorical_features = [
    'PREVENTION_KEY', 'CURRENCY', 'PAYMENT_FREQUENCY', 'BUSINESS_TYPE',
    'CREDIT_TYPE', 'ACCOUNT_TYPE', 'RESPONSABILITY_TYPE'
    ]
datetime_features = [
    'INQUIRY_TIME', 'INQUIRY_DATE', 'UPDATE_DATE', 'LOAN_OPENING_DATE', 
    'LOAN_CLOSING_DATE', 'WORST_DELAY_DATE', 'REPORT_DATE',
    'LAST_PURCHASE_DATE', 'LAST_PAYMENT_DATE'
    ]